services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - '9411:9411'

volumes:
  postgres: